version: '2'

services:
  zoo1:
    image: hyperledger/fabric-zookeeper:amd64-0.4.14
    restart: always
    hostname: zoo1
    container_name: zoo1
    ports:
    - 2181:2181
    volumes:
    - "/opt/zoo/:/data"
    - "/opt/zoo/datalog:/datalog"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - br17219

  zoo2:
    image: hyperledger/fabric-zookeeper:amd64-0.4.14
    restart: always
    hostname: zoo2
    container_name: zoo2
    ports:
    - 2181:2181
    volumes:
    - "/opt/zoo/:/data"
    - "/opt/zoo/datalog:/datalog"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - br17219

  zoo3:
    image: hyperledger/fabric-zookeeper:amd64-0.4.14
    restart: always
    hostname: zoo3
    container_name: zoo3
    ports:
    - 2181:2181
    volumes:
    - "/opt/zoo/:/data"
    - "/opt/zoo/datalog:/datalog"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - br17219

  kafka1:
    image: hyperledger/fabric-kafka:amd64-0.4.14
    restart: always
    hostname: kafka1
    container_name: kafka1
    depends_on:
      - zoo1
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
    volumes:
    - /opt/kafka/:/kafka
    external_links:
    - zoo1
    - zoo2
    - zoo3
    networks:
      - br17219

  kafka2:
    image: hyperledger/fabric-kafka:amd64-0.4.14
    restart: always
    hostname: kafka2
    container_name: kafka2
    ports:
    - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
    volumes:
    - /opt/kafka/:/kafka
    external_links:
    - zoo1
    - zoo2
    - zoo3
    networks:
      - br17219

  kafka3:
    image: hyperledger/fabric-kafka:amd64-0.4.14
    restart: always
    hostname: kafka3
    container_name: kafka3
    ports:
    - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka3
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
    volumes:
    - /opt/kafka/:/kafka
    external_links:
    - zoo1
    - zoo2
    - zoo3
    networks:
      - br17219

networks:
  br17219: